### ISSUE TITLE
A question about the zener diodes, and a mistake.

### ISSUE THREAD

**Issue by myst729** [stevennguyen/framework#1]
**The issue**: In your schematic, it looks like you connect two Schottky diodes to USB D+/D-. This leads me to the wrong direction in the first place. Then I checked the BOM and find out they are Zener diodes. They are slightly different.

![image](https://user-images.githubusercontent.com/519733/128973308-2acccee4-90f0-47a1-8473-b1bed45500d8.png)

**The question**: I'm an amateur hobbyist so this question might be stupid. Your current design adopts a 16Mhz crystal, which makes the MCU runs under 5V. Then you put two Zener diodes to limit the voltage . Why not use an 8Mhz crystal so that the MCU runs under 3.3V?

**Comment by stevennguyen** [comment]
Hey Leo, thanks for catching that!

Since the ATmega328P has no native USB driver, the firmware uses [V-USB](https://github.com/obdev/v-usb), which requires the higher clock speed.

**Comment by stevennguyen** [comment]
Fixed issue: https://github.com/stevennguyen/framework/commit/9c14dc4136175cf56bad0931c2c7604f0b292a57

**Comment by myst729** [comment]
I also have a question about the D+/D- pins in USBasploader, https://github.com/baerwolf/USBaspLoader/issues/22, any ideas?

**Comment by stevennguyen** [comment]
It seems to me that INT0 is used because it has higher priority than INT1. I think you _can_ use INT1, but you will need to change the code to do it. By using INT1 for USB, you're pretty much giving up INT0, since any signal on INT0 will produce unreliable USB communication.
